name: Publish-Schema

on:
  push:
    branches:
      - master
      - production

jobs:
  publish_schema:
    runs-on: ubuntu-latest
    steps:
      - name: Testing github branch name
        run: echo ${GITHUB_REF##*/}
             echo ${DEVOPS_DEV_AWS_ACCESS_KEY_ID}
